[package]
name = "cli-music"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.30"
crossterm = "0.29"
apple-music = "0.11"
image = "0.25"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
color-eyre = "0.6"
